services:
  event-hub:
    build:
      target: development
    image: event-hub-development
    container_name: event-hub-development
    ports:
      - "9229:9229"
    volumes:
      - ./src:/home/node/src
      - ./package.json:/home/node/package.json
    networks:
      - event-hub
    depends_on:
      localstack:
        condition: service_healthy
      mongo:
        condition: service_started
      event-hub-client:
        condition: service_started
    environment:
      AWS_REGION: eu-west-2
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_SNS_TOPIC_ARN: arn:aws:sns:eu-west-2:000000000000:topic1
      AWS_SQS_QUEUE_URL: http://localstack:4566/000000000000/queue1
      AWS_ENDPOINT_URL: http://localstack:4566
      MONGODB_URI: mongodb://mongo:27017/event-hub

  event-hub-client:
    build:
      context: ./client
      target: development
    image: event-hub-client-development
    container_name: event-hub-client-development
    volumes:
      - ./client/src:/home/node/src
      - ./client/package.json:/home/node/package.json
    networks:
      - event-hub
    depends_on:
      localstack:
        condition: service_healthy
    environment:
      AWS_REGION: eu-west-2
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_SNS_TOPIC_ARN: arn:aws:sns:eu-west-2:000000000000:topic1
      AWS_ENDPOINT_URL: http://localstack:4566

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      LS_LOG: warn
      SERVICES: sqs,sns
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
    volumes:
      - ./scripts/localstack.sh:/etc/localstack/init/ready.d/localstack.sh
      - localstack-data:/var/lib/localstack
    healthcheck:
      test: ['CMD', 'curl', 'localhost:4566']
      interval: 5s
      start_period: 5s
      retries: 3
    networks:
      - event-hub

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - event-hub
    volumes:
      - mongodb-data:/data/db

networks:
  event-hub:
    driver: bridge
    name: event-hub

volumes:
  mongodb-data:
  localstack-data:
