services:
  event-hub:
    build:
      target: development
    image: event-hub-development
    container_name: event-hub-development
    ports:
      - "9229:9229"
    volumes:
      - ./src:/home/node/src
      - ./package.json:/home/node/package.json
    networks:
      - event-hub
    depends_on:
      localstack:
        condition: service_healthy
    environment:
      AWS_REGION: eu-west-2
      AWS_SNS_TOPIC_ARN: arn:aws:sns:eu-west-2:000000000000:topic1
      AWS_SQS_QUEUE_URL: http://localstack:4566/000000000000/queue1

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - SERVICES=sqs,sns
    volumes:
      - ./scripts/localstack.sh:/etc/localstack/init/ready.d/localstack.sh
    healthcheck:
      test: ['CMD', 'curl', 'localhost:4566']
      interval: 5s
      start_period: 5s
      retries: 3


networks:
  event-hub:
    driver: bridge
    name: event-hub
